# Generated by Django 5.2.7 on 2025-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meeting_created_by_userprofile_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('live', 'Live'), ('ended', 'Ended')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='code_visible_to_members',
            field=models.BooleanField(default=False),
        ),
    ]
