# Generated by Django 4.2.11 on 2025-11-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.CharField(blank=True, default='', max_length=120)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='home.meeting')),
            ],
        ),
    ]
